#Required sudo for docker
sudo: required
language: bash

env:
  - container_id=${container_id:-$timestamp}
 
services:
  - docker

before_install:
#pull the image from Docker Hub for the OS under test
  - docker pull sath89/oracle-12c

script:
#create a random file to store the container
  - export container_id=$(date +%s)
  - export cleanup=false

# Run container detached
  - sudo docker run -d -p 8080:8080 -p 1521:1521 sath89/oracle-12c
  - sudo docker exec -it --user root $(docker ps -aq) /bin/bash -c "mkdir -P /docker-entrypoint-initdb.d"
  - touch oracle.log
  - sudo docker logs --timestamps $(docker ps -aq)
  - sleep 500
  - sudo docker logs --timestamps $(docker ps -aq)
  - sudo docker exec -it --user root $(docker ps -aq) /bin/bash -c "apt-get update;apt-get -y install git" 
  - sudo docker exec -it --user oracle $(docker ps -aq) /bin/bash -c "netstat -nlpt" 
  - sudo docker exec -it --user oracle $(docker ps -aq) /bin/bash -c "netstat -nlpt;git clone https://github.com/hemanth22/Oracle_database.git;ls -la;cd Oracle_database;./login.sh"
  - sudo docker stop $(docker ps -aq)
  - sudo docker rm $(docker ps -aq)
  - sudo docker rmi $(docker images -aq)
  #- docker run -it --name ${container_id} centos:7 /bin/bash -c "yum -y install epel-release;yum -y install git;git clone https://github.com/hemanth22/CSVToCustomDSV.git;cd CSVToCustomDSV;./csv2dsv.sh"

notifications:
 slack:
   rooms:
     - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#mygitrepos
