#Required sudo for docker
sudo: required
language: bash

env:
  - container_id=${container_id:-$timestamp}
 
services:
  - docker

before_install:
#pull the image from Docker Hub for the OS under test
  - docker pull quay.io/maksymbilenko/oracle-12c

script:
#create a random file to store the container
  - export container_id=$(date +%s)
  - export cleanup=false

# Run container detached
  - docker run -d -p 8080:8080 -p 1521:1521 quay.io/maksymbilenko/oracle-12c
  - docker logs --timestamps $(docker ps -aq)
  - sleep 500
  - docker logs --timestamps $(docker ps -aq)
  - docker exec -it --user root $(docker ps -aq) /bin/bash -c "apt update;apt -y install git"
  - docker exec -it --user root $(docker ps -aq) /bin/bash -c "git clone https://github.com/hemanth22/Oracle_database.git"
  - docker exec -it --user root $(docker ps -aq) /bin/bash -c "chmod -R 777 Oracle_database;cd /Oracle_database;ls -la"
  - docker exec -it --user oracle $(docker ps -aq) /bin/bash -c "netstat -nlpt" 
  - docker exec -it --user oracle $(docker ps -aq) /bin/bash -c "ls && cd Oracle_database && ls && bash login.sh"
  - docker stop $(docker ps -aq)
  - docker rm $(docker ps -aq)
  - docker rmi $(docker images -aq)

notifications:
 slack:
   rooms:
     - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#mygitrepos
