version: "3.7"

services:
  oracle:
    image: sath89/oracle-12c:latest
    ports:
      - "8080:8080"
      - "1521:1521"
    stop_grace_period: 1m0s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - fronter
  jsp:
    image: jspdbdocker_dbjsp:latest
    ports:
      - "8888:8080"
    networks:
      - fronter
    depends_on:
      - oracle
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  fronter:
