--------------------------------------------------------
--  File created - Sunday-October-23-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUPPLIERS
--------------------------------------------------------

  CREATE TABLE "SCOTT"."SUPPLIERS" 
   (	"SUPPLIERID" NUMBER(*,0), 
	"SUPPLIERNAME" VARCHAR2(255 BYTE), 
	"CONTACTNAME" VARCHAR2(255 BYTE), 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"CITY" VARCHAR2(255 BYTE), 
	"POSTALCODE" VARCHAR2(255 BYTE), 
	"COUNTRY" VARCHAR2(255 BYTE), 
	"PHONE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.SUPPLIERS
SET DEFINE OFF;
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (1,'Exotic Liquid','Charlotte Cooper','49 Gilbert St.','Londona','EC1 4SD','UK','(171) 555-2222');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (2,'New Orleans Cajun Delights','Shelley Burke','P.O. Box 78934','New Orleans','70117','USA','(100) 555-4822');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (3,'Grandma Kelly''s Homestead','Regina Murphy','707 Oxford Rd.','Ann Arbor','48104','USA','(313) 555-5735');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (4,'Tokyo Traders','Yoshi Nagase','9-8 Sekimai Musashino-shi','Tokyo','100','Japan','(03) 3555-5011');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (5,'Cooperativa de Quesos ''Las Cabras''','Antonio del Valle Saavedra','Calle del Rosal 4','Oviedo','33007','Spain','(98) 598 76 54');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (6,'Mayumi''s','Mayumi Ohno','92 Setsuko Chuo-ku','Osaka','545','Japan','(06) 431-7877');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (7,'Pavlova',' Ltd.','Ian Devling 74 Rose St. Moonie Ponds ','Melbourne','3058','Australia','(03) 444-2343');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (8,'Specialty Biscuits',' Ltd.','Peter Wilson 29 King''s Way','Manchester','M14 GSD','UK','(161) 555-4448');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (9,'PB Knäckebröd AB','Lars Peterson','Kaloadagatan 13','Göteborg','S-345 67','Sweden','031-987 65 43');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (10,'Refrescos Americanas LTDA','Carlos Diaz','Av. das Americanas 12.890','São Paulo','5442','Brazil','(11) 555 4640');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (11,'Heli Süßwaren GmbH & Co. KG','Petra Winkler','Tiergartenstraße 5','Berlin','10785','Germany','(010) 9984510');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (12,'Plutzer Lebensmittelgroßmärkte AG','Martin Bein','Bogenallee 51','Frankfurt','60439','Germany','(069) 992755');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (13,'Nord-Ost-Fisch Handelsgesellschaft mbH','Sven Petersen','Frahmredder 112a','Cuxhaven','27478','Germany','(04721) 8713');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (14,'Formaggi Fortini s.r.l.','Elio Rossi','Viale Dante 75','Ravenna','48100','Italy','(0544) 60323');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (15,'Norske Meierier','Beate Vileid','Hatlevegen 5','Sandvika','1320','Norway','(0)2-953010');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (16,'Bigfoot Breweries','Cheryl Saylor','3400 - 8th Avenue Suite 210','Bend','97101','USA','(503) 555-9931');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (17,'Svensk Sjöföda AB','Michael Björn','Brovallavägen 231','Stockholm','S-123 45','Sweden','08-123 45 67');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (18,'Aux joyeux ecclésiastiques','Guylène Nodier','203  Rue des Francs-Bourgeois',' Paris','75004','France','(1) 03.83.00.68');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (19,'New England Seafood Cannery','Robb Merchant','Order Processing Dept. 2100 Paul Revere Blvd.','Boston','2134','USA','(617) 555-3267');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (20,'Leka Trading','Chandra Leka','471 Serangoon Loop  Suite #402 ','Singapore','512','Singapore','555-8787');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (21,'Lyngbysild','Niels Petersen','Lyngbysild Fiskebakken 10','Lyngby','2800','Denmark','43844108');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (22,'Zaanse Snoepfabriek','Dirk Luchte','Verkoop Rijnweg 22','Zaandam','9999 ZZ','Netherlands','(12345) 1212');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (23,'Karkki Oy','Anne Heikkonen','Valtakatu 12','Lappeenranta','53120','Finland','(953) 10956');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (24,'G''day',' Mate','Wendy Mackenzie 170 Prince Edward Parade Hunter''s Hill ','Sydney','2042','Australia','(02) 555-5914');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (25,'Ma Maison','Jean-Guy Lauzon','2960 Rue St. Laurent','Montréal','H1J 1C3','Canada','(514) 555-9022');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (26,'Pasta Buttini s.r.l.','Giovanni Giudici','Via dei Gelsomini 153 ','Salerno','84100','Italy','(089) 6547665');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (27,'Escargots Nouveaux','Marie Delamare','22  rue H. Voiron ','Montceau','71300','France','85.57.00.07');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (28,'Gai pâturage','Eliane Noz','Bat. B 3  rue des Alpes',' Annecy','74000','France','38.76.98.06');
Insert into SCOTT.SUPPLIERS (SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY,PHONE) values (29,'Forêts d''érables','Chantal Goulet','148 rue Chasseur','Ste-Hyacinthe','J2S 7S8','Canada','(514) 555-2955');
--------------------------------------------------------
--  Constraints for Table SUPPLIERS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SUPPLIERS" MODIFY ("SUPPLIERID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SUPPLIERS" MODIFY ("SUPPLIERNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SUPPLIERS" MODIFY ("CONTACTNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SUPPLIERS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SUPPLIERS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SUPPLIERS" MODIFY ("POSTALCODE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SUPPLIERS" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SUPPLIERS" MODIFY ("PHONE" NOT NULL ENABLE);
