version: 2
jobs:
  build:
    working_directory: /app
    docker:
      #- image:18.06.0-ce-git
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            apk --no-cache add curl
            pip install wget
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Pull oracle 12c database docker image from quay.
          command: docker pull quay.io/maksymbilenko/oracle-12c
      - run:
          name: Run docker container.
          command: docker run -d -p 8080:8080 -p 1521:1521 quay.io/maksymbilenko/oracle-12c
      - run:
          name: Check docker inital log.
          command: docker logs --timestamps $(docker ps -aq)
      - run:
          name: Sleep untill container is up and running.
          command: sleep 300
      - run:
          name: Check docker up status.
          command: docker logs --timestamps $(docker ps -aq)
      - run:
          name: Check docker operating system.
          command: docker exec -it --user root $(docker ps -aq) /bin/bash -c "cat /etc/*release"
      - run:
          name: Installing pre-requistes inside the docker.
          command: docker exec -it --user root $(docker ps -aq) /bin/bash -c "yum update -y;yum -y install git;yum -y install net-tools"
      - run:
          name: Cloning project inside the docker.
          command: docker exec -it --user root $(docker ps -aq) /bin/bash -c "git clone https://github.com/hemanth22/Oracle_database.git"
      - run:
          name: Check project content inside the docker.
          command: docker exec -it --user root $(docker ps -aq) /bin/bash -c "chmod -R 777 Oracle_database;cd /Oracle_database;ls -la"
      - run:
          name: Check docker connections.
          command: docker exec -it --user oracle $(docker ps -aq) /bin/bash -c "netstat -nlpt"
      - run:
          name: Initializing my own script.
          command: docker exec -it --user oracle $(docker ps -aq) /bin/bash -c "ls && cd Oracle_database && ls && bash login.sh"
      - run:
          name: Session closure after the test.
          command: docker stop $(docker ps -aq)
      - run:
          name: Remove container.
          command: docker rm $(docker ps -aq)
      - run:
          name: Remove image..
          command: docker rmi $(docker images -aq)
